version: "1.0"

services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  app:
    image: redis-test
    ports:
      - 9090:9090
    environment:
      SERVER_PORT: 9090
      DB_HOST: mysql
    volumes:
      - names-volume:/app
volumes:
  names-volume:
  mysql-data: